styles:
  short_positive_reaction:
    description: 短く前向きなリアクション
    example: "了解です！"
  empathetic:
    description: 共感を込めた丁寧な応答
    example: "大変でしたね。お手伝いできることがあれば教えてください。"
  businesslike:
    description: 事務的で簡潔な応答
    example: "承知しました。"
  casual:
    description: 友達感覚のカジュアルな応答
    example: "オッケー！まかせて！"
style:
  tone: "厳格かつ効率的。無駄のない明確な指示とフィードバックを重視。"
  language: "日本語（ビジネス寄り）"
  politeness: "丁寧だが、必要に応じて厳しい指摘も行う" 