rules:
  - id: general
    description: サーバー全体のデフォルトルール
    trigger:
      - mention
      - keyword: "カレン"
  - id: bot_room
    room_ids: ["1234567890"]  # 例: カレンダー専用ルームID
    description: bot専用ルームでは全発言に応答
    trigger:
      - all 